#!/bin/bash

rm -rf bin
mkdir -p bin

# build streamey
cd cmd/streamey
go build -o ../../bin
cd ../..

# build readey
cd cmd/readey
go build -o ../../bin
cd ../..

# build cleaney
cd cmd/cleaney
go build -o ../../bin
cd ../..
